= Mask (Gangle's Song) (feat. Marissa Lenti)

:category: humour
:date: 2026-05-12
:summary: Gangle's song from YouTube
:tags: The Amazing Digital Circus

[source, text]
feel a little bit crazy lately
wanna set the whole world on fire
should i jump out of a window, maybe
no instead i'll just smile smile smile

[source, text]
what's inside
i gotta find
don't wanna hide
the real me

== but the world is fucking bleak

[source, text]
so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

[source, text]
and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

[source, text]
people tell me i have a problem
cause i wanna stay in all night
up and down i get low so often
need a new mask to take me high

[source, text]
what's inside
i gotta find
don't wanna hide
the real me 

== but the world is fucking bleak

[source, text]
so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

[source, text]
and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

== wanna take your mask away
[source, text]
no i like it
it's okay

== but you're crying everyday
[source, text]
i feel it in a silly way

== bi-bi-polarity
[source, text]
and it looks so good on me

== boy i'm so glad i asked
[source, text]
that is why i wear a ...

[source, text]
insecurity
it's a part of me
maybe that's okay

[source, text]
i want you to see
the hidden part of me
should i take mask off

== NO

[source, text]
so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

[source, text]
and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

[source, text]
and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

[source, text]
feel a little bit crazy lately
