= Mask (Gangle's Song) (feat. Marissa Lenti)

:date: 2026-05-12
:description: Gangle's song from YouTube

feel a little bit crazy lately
wanna set the whole world on fire
should i jump out of a window, maybe
no instead i'll just smile smile smile

what's inside
i gotta find
don't wanna hide
the real me

(but the world is fucking bleak)

so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

people tell me i have a problem
cause i wanna stay in all night
up and down i get low so often
need a new mask to take me high

what's inside
i gotta find
don't wanna hide
the real me 

(but the world is fucking bleak)

so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

(wanna take your mask away)
no i like it
it's okay

(but you're crying everyday)
i feel it in a silly way

(bi-bi-polarity)
and it looks so good on me

(boy i'm so glad i asked)
that is why i wear a ...

insecurity
it's a part of me
maybe that's okay

i want you to see
the hidden part of me
should i take mask off

(NO)

so i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

and i mask mask mask
how i feel feel feel
til i don't don't don't know 
what is real real real

and so when i feel down
and all my thoughts spin round
i work it out out out
i work it out

feel a little bit crazy lately
