[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ghp-import>=2.1.0",
    "invoke>=2.2.0",
    "pelican>=4.11.0",
    "pelican-sitemap>=1.2.1"
]
